### ISSUE TITLE
Asumir que N-coloreable es NP-completo

### ISSUE THREAD

**Issue by jgespinosa10** [juanreutter/L-gica2020#1]
En las notas vimos que SAT y 3-coloreabilidad es NP-completo. Luego, quedo como ejercicio demostrar que 4-coloreabilidad es NP-completo.
¿Podemos para la tarea asumir que el N-coloreable es NP-completo?

**Comment by juanreutter** [comment]
Puedes asumir que N-colorabilidad es NP-completo para cualquier N>=3. 1-colorabilidad es trivial y 2-colorabilidad de hecho sabemos que está en P (tienes que chequear que el grafo sea bipartito). 

Pero ojo que en todos estos problemas el N está dado, fijo, no se recibe como input.

**Comment by Pipelao** [comment]
@juanreutter Hola profesor. ¿A qué se refiere y en qué afecta si N está dado y no se recibe como input? 

Gracias.

**Comment by juanreutter** [comment]
No es el mismo problema, es lo que tienes que ver!

**Comment by Pipelao** [comment]
Mmm, ¿pero no que la palabra en el lenguaje ya viene como lista? Entonces el input correspondería a una palabra que ya tiene definidas las variables P,V,M y S o no?

**Comment by juanreutter** [comment]
Claro, pero en 3-colorabilidad nunca viene un 3 en la palabra, viene el puro grafo

**Comment by Pipelao** [comment]
@juanreutter Ahhh cierto, gracias.

**Comment by Jaluco** [comment]
Es valido construir una maquina que dependiendo de un N aplique N-coloreabilidad?

**Comment by juanreutter** [comment]
Claro, pero tendrías que mostrar primero que ese problema es NP-duro (eso es bien simple)
