### ISSUE TITLE
Input problema T3

### ISSUE THREAD

**Issue by fgbruna** [juanreutter/L-gica2020#2]
Como se vería una instancia del problema de la tarea? sería algo así como (P, M , S, V) ?. 
Pregunto esto ya que en particular al reducir otro problema a este no me queda claro que inputs hay que especificar al transformarlo en una instancia de nuestro problema.

**Comment by juanreutter** [comment]
Si, asi se ve. Al reducir de L a ese problema, si partes de un w en L tienes que generar un string que pertenezca a ese problema, osea, especificar todas las partes del input.
