### ISSUE TITLE
3COL en NP

### ISSUE THREAD

**Issue by Pipelao** [juanreutter/L-gica2020#3]
Hola,

Tengo preguntas acerca de la demostración de que 3-COL está en NP. A continuación muestro una imagen de parte de la demostración de la cual tengo dudas.
![3col](https://user-images.githubusercontent.com/26421921/84839632-8cb4a800-b00b-11ea-93aa-73e130958b98.PNG)

1. En primer lugar no entiendo a qué se refiere con que se construye una máquina sobre el lenguaje {r,b,a,0,1}. Entiendo que sean tres colores, ¿pero por qué agrega el 0 y 1? o ¿se refiere a que se traducirán los colores en binario cómo lo hizo en las notas de la semana 7? Porque si es así el largo sería 3*n y no n, ¿o no?

2. Con respecto a la parte en que menciona que:

> Una máquina que chequee que esa coloración es válida

¿Cómo sabemos que ese procedimiento es polinomial?

Gracias.

**Comment by juanreutter** [comment]
1. Sobre el alfabeto. Puse ese alfabeto grande por que pensaba que iba a ser mas simple, pero puedes pensar en la codificacion binaria, y claro, ahi el largo es 3*n. En el caso de los colores, la maquina usa r,b,a para representar colores, pero luego debes trabajar en el grafo, y eso lo hacemos con ceros y unos.

2. No sabemos, pero podemos argumentarlo: lo unico que hay que hacer es chequear, arista por arista, que tengan el mismo color. Eso es un numero constante de lecturas del input por cada arista, lo que va a estar en O(n^2), al igual como ibamos procesando la formula para resolver EVAL de formulas proposicionales.

**Comment by Pipelao** [comment]
1. Ahh creo que ahora entendí lo del alfabeto, ¿entonces era como asignar r,a,b a cada nodo como de forma inmediata sin pasarlo a binario? Aunque supongo que en algún momento todo tiene que estar en binario o no?

2. Perfecto, gracias.

**Comment by juanreutter** [comment]
claro, tal como dices. 
No realmente, podemos definir lenguajes sobre otros alfabetos también. Pero claro, una comparación más estándar sería solo pensar en el alfabeto binario.

**Comment by Pipelao** [comment]
@juanreutter Perfecto, gracias.
