### ISSUE TITLE
[T3] Restricciones del problema

### ISSUE THREAD

**Issue by jmwielandt** [juanreutter/L-gica2020#5]
Hola, quería saber si...

1. ¿El `I = |invitados|` es el P del que hablan en todo el resto del enunciado?
2. ¿Todas las mesas tienen que tener la misma cantidad de sillas?

Gracias

**Comment by juanreutter** [comment]
1. Si perdón!! ese I debiese ser una P. 

2. Si (eso hace más simple todo)

**Comment by Pipelao** [comment]
@juanreutter ¿pero puede ser que algunas mesas y/o sillas estén vacías?

**Comment by juanreutter** [comment]
si

**Comment by Pipelao** [comment]
@juanreutter gracias.
