### ISSUE TITLE
Codificación grafo 3-COL

### ISSUE THREAD

**Issue by Pipelao** [juanreutter/L-gica2020#6]
Hola @juanreutter ,

Tengo una pregunta acerca de la codificación del grafo 3-COL en las notas de la semana 9 que muestro a continuación:

![codificacion](https://user-images.githubusercontent.com/26421921/85207910-2b862080-b2fa-11ea-96fd-30cff36d187a.PNG)

No entiendo por qué C(G) = 1^n0v, ¿para qué es ese 1^n?, ¿es la coloración del grafo? Porque si es la coloración, entonces ¿por qué se describe nuevamente el 1^n0C(G)? Básicamente mi pregunta va a por qué hay dos 1^n y qué representa cada uno.

Gracias de antemano.

**Comment by juanreutter** [comment]
Una cosa es C(G). La forma estándar de codificar grafos es mostrar en unario la cantidad de nodos (digamos n) y luego en un string de tamaño n^2 con ceros y unos que nos diga qué arista (de las n^2 posibles) está en el grafo y cual no. Ojo que necesitas saber de antemano la cantidad de nodos, por que si no no vas a saber hasta donde parsear el string binario de las aristas. 

Luego está ese 1^n adicional que uso para la coloración. Tienes toda la razon en que podría haber usado el mismo 1^n de C(G), pero no lo hize así para poder seguir hablando de C(G) nomas.

**Comment by Pipelao** [comment]
Ahhh ok, gracias @juanreutter .
